### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by khholtz** [awslabs/lambda-refarch-imagerecognition#1]
When I enter npm start, it fails with the following errors:

app/config.ts(2,13): error TS1005: ';' expected.
app/config.ts(3,67): error TS1005: ';' expected.
app/config.ts(9,1): error TS1128: Declaration or statement expected.

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! serverless-image-proc-backend@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the serverless-image-proc-backend@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless-image-proc-backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless-image-proc-backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless-image-proc-backend
npm ERR! There is likely additional logging output above.

**Comment by angelarw** [comment]
Hi khholtz, 

looks like it's complaining about your "app/config.ts" file. When you did the step to fill in the values from the CloudFormation stack output, did you only overwrite the strings that say "TO_BE_REPLACED" (see the [original config.ts file](https://github.com/awslabs/lambda-refarch-imagerecognition/blob/master/webapp/app/config.ts) ?

**Comment by khholtz** [comment]
You are indeed correct, in addition to the "TO_BE_REPLACED" I overwrote the _string_ above.  Working now.  Thank you!
