### ISSUE TITLE
Unable to produce prod build

### ISSUE THREAD

**Issue by frazer-jamieson** [awslabs/lambda-refarch-imagerecognition#3]
Hello,

I have successfully deployed this locally and want to say thanks for some great code!

I am trying `npm build -dist` to produce the code to deploy the web app to an S3 bucket as a static website rather than have this working locally.

I am getting no error at the command line, instead npm doesn't produce a prod build/populated dist folder.

Any ideas please?

Many thanks :)

**Comment by angelarw** [comment]
hi frazer-jamieson, 

I purposely didn't provide utility to package the webapp up for hosting on s3, as the app wasn't meant to be hosted publicly as-is, but just to give a frontend to help you understand what's going on in the backend. (e.g. it uses accesskey/secretkey pair for authenticating with AWS services). 

what's the reason you want to host this on a static website?

**Comment by frazer-jamieson** [comment]
Hi Angela,

I'm an AWS architect and also learning Angular 2: preparing the app so 
that I can host it on S3 is for learning every step of the solution and 
having a test-bed to experiment with.  It doesn't need to be 'public' 
for long, I'm just learning and want to see this in action and then 
reverse engineer each step to learn more.

Here's my LinkedIn so that you can see my experience/interest: 
www.linkedin.com/in/frazerj

I'd like to thank you again for the code which is very exciting!

Although not new to AWS, I am new to Angular 2 , so am not sure how to 
make a prod distribution other than npm build -prod!

Many thanks

Frazer

**Comment by frazer-jamieson** [comment]
Hi Angela,

Any news on this please?

Many thanks

Frazer

**Comment by angelarw** [comment]
Hi Frazer, 

I currently don't have the bandwidth to work on this yet, but I suggest you to take a look at some approaches discussed here if you want to learn how to deploy an angular2 app: http://stackoverflow.com/questions/36285064/how-do-i-actually-deploy-an-angular-2-typescript-systemjs-app 

Angela
